spring.application.name=demo

spring.data.web.pageable.serialization-mode=via-dto
spring.servlet.multipart.file-size-threshold=1MB
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
server.tomcat.max-swallow-size=-1
server.tomcat.connection-timeout=300000

spring.datasource.url=jdbc:mysql://localhost:3306/demo_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.storage.max-quota=104857600
app.storage.upload-dir=uploads

app.jwt.secret=ClaveMaestraSuperSecretaDeCloudCrypt2026ParaTFGSeguroMapeadaDesdeProperties
app.jwt.expiration-ms=7200000

spring.jpa.properties.hibernate.default_batch_fetch_size=20