services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_storage_service
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_db
      - MYSQL_USER=user_tfg
      - MYSQL_PASSWORD=pass_tfg
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local