spring.application.name=demo
spring.data.web.pageable.serialization-mode=via-dto
server.tomcat.max-swallow-size=-1
server.tomcat.connection-timeout=300000

spring.datasource.url=jdbc:h2:mem:setup_db;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.crypto.hash-algorithm=SHA-256
app.crypto.symmetric-algorithm=AES/GCM/NoPadding
app.crypto.asymmetric-key-size=2048
app.crypto.salt-suffix=-cloudcrypt

spring.servlet.multipart.file-size-threshold=1MB
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
app.storage.max-quota=104857600
app.storage.upload-dir=uploads

app.jwt.secret=ClaveMaestraSuperSecretaDeCloudCrypt2026ParaTFGSeguroMapeadaDesdeProperties
app.jwt.expiration-ms=7200000
spring.jpa.properties.hibernate.default_batch_fetch_size=20